# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('is_eliminated', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('in_round', models.IntegerField(default=0)),
                ('max_movies_per_user', models.IntegerField(default=3)),
                ('has_winner', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UserInSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieselector.Selection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voting_round', models.IntegerField()),
                ('is_upvote', models.BooleanField(default=False)),
                ('movie_in_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieselector.MovieInSelection')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movieselector.Selection')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='selection',
            name='users',
            field=models.ManyToManyField(through='movieselector.UserInSelection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movieinselection',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movieselector.Selection'),
        ),
    ]
